export const jobs = {
    "Adele": { archetype: ["warrior"], faction: "flora" },
    "Angelic Buster": { archetype: ["pirate"], faction: "nova" },
    "Aran": { archetype: ["warrior"], faction: "hero" },
    "Arch Mage (Fire, Poison)": { archetype: ["mage"], faction: "explorer" },
    "Arch Mage (Ice, Lightning)": { archetype: ["mage"], faction: "explorer" },
    "Ark": { archetype: ["pirate"], faction: "flora" },
    "Battle Mage": { archetype: ["mage"], faction: "resistance" },
    "Bishop": { archetype: ["mage"], faction: "explorer" },
    "Blaster": { archetype: ["warrior"], faction: "resistance" },
    "Blaze Wizard": { archetype: ["mage"], faction: "cygnus knight" },
    "Bowmaster": { archetype: ["archer"], faction: "explorer" },
    "Buccaneer": { archetype: ["pirate"], faction: "explorer" },
    "Cadena": { archetype: ["thief"], faction: "nova" },
    "Cannoneer": { archetype: ["pirate"], faction: "explorer" },
    "Corsair": { archetype: ["pirate"], faction: "explorer" },
    "Dark Knight": { archetype: ["warrior"], faction: "explorer" },
    "Dawn Warrior": { archetype: ["warrior"], faction: "cygnus knight" },
    "Demon Avenger": { archetype: ["warrior"], faction: "resistance" },
    "Demon Slayer": { archetype: ["warrior"], faction: "resistance" },
    "Dual Blade": { archetype: ["thief"], faction: "explorer" },
    "Evan": { archetype: ["mage"], faction: "hero" },
    "Hayato": { archetype: ["warrior"], faction: "sengoku" },
    "Hero": { archetype: ["warrior"], faction: "explorer" },
    "Hoyoung": { archetype: ["thief"], faction: "anima" },
    "Illium": { archetype: ["mage"], faction: "flora" },
    "Kain": { archetype: ["archer"], faction: "nova" },
    "Kaiser": { archetype: ["warrior"], faction: "nova" },
    "Kanna": { archetype: ["mage"], faction: "sengoku" },
    "Khali": { archetype: ["thief"], faction: "flora" },
    "Kinesis": { archetype: ["mage"], faction: "friendstory" },
    "Lara": { archetype: ["mage"], faction: "anima" },
    "Len": { archetype: ["warrior"], faction: "star guardian" },
    "Luminous": { archetype: ["mage"], faction: "hero" },
    "Lynn": { archetype: ["warrior"], faction: "star guardian" },
    "Marksman": { archetype: ["archer"], faction: "explorer" },
    "Mechanic": { archetype: ["pirate"], faction: "resistance" },
    "Mercedes": { archetype: ["archer"], faction: "hero" },
    "Mihile": { archetype: ["warrior"], faction: "cygnus knight" },
    "Mo Xuan": { archetype: ["thief"], faction: "jianghu" },
    "Night Lord": { archetype: ["thief"], faction: "explorer" },
    "Night Walker": { archetype: ["thief"], faction: "cygnus knight" },
    "Paladin": { archetype: ["warrior"], faction: "explorer" },
    "Pathfinder": { archetype: ["archer"], faction: "explorer" },
    "Phantom": { archetype: ["thief"], faction: "hero" },
    "Shade": { archetype: ["thief"], faction: "hero" },
    "Shadower": { archetype: ["thief"], faction: "explorer" },
    "Sia Astelle": { archetype: ["mage"], faction: "star guardian" },
    "Thunder Breaker": { archetype: ["pirate"], faction: "cygnus knight" },
    "Wild Hunter": { archetype: ["archer"], faction: "resistance" },
    "Wind Archer": { archetype: ["archer"], faction: "cygnus knight" },
    "Xenon": { archetype: ["pirate", "thief"], faction: "resistance" },
    "Zero": { archetype: ["warrior"], faction: "child of god" },
};

export const emptyCharacter = {
    job: "",
    archetype: "",
    faction: "",
    level: 1,
    ring1: { name: "ring" },
    ring2: { name: "ring" },
    ring3: { name: "ring" },
    ring4: { name: "ring" },
    pocket: { name: "pocket" },
    pendant1: { name: "pendant" },
    pendant2: { name: "pendant" },
    weapon: { name: "weapon" },
    belt: { name: "belt" },
    hat: { name: "hat" },
    face: { name: "face" },
    eye: { name: "eye acc" },
    top: { name: "top" },
    bottom: { name: "bottom" },
    shoes: { name: "shoes" },
    ear: { name: "ear acc" },
    shoulder: { name: "shoulder" },
    gloves: { name: "gloves" },
    android: { name: "android" },
    emblem: { name: "emblem" },
    badge: { name: "badge" },
    medal: { name: "medal" },
    secondary: { name: "sub weapon" },
    cape: { name: "cape" },
    heart: { name: "heart" },
}